name: Track Shipment Status

on:
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Chrome and Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install zendriver
      run: pip install zendriver==0.4.3
    
    - name: Run with Xvfb
      env:
        ZENDRIVER_NO_SANDBOX: "true"
        ZENDRIVER_LOG_LEVEL: "INFO"
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" python tracker.py
