name: Track Shipment Status

on:
  workflow_dispatch:

env:
  TRACKING_NUMBER: '347720741487'

jobs:
  track:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install zendriver
      run: pip install zendriver==0.4.3
    
    - name: Run tracking script
      env:
        ZENDRIVER_NO_SANDBOX: "true"
        ZENDRIVER_LOG_LEVEL: "INFO"
      run: python tracker.py
